### ISSUE TITLE
Download option fails to appear on the context menu

### ISSUE THREAD

**Issue by bea831333** [HassakuTb/TwitterImageDownloader2#16]
Currently using firefox 120.0.1, after the latest update of both the browser and the extension I was not able to see the download option on twitter images anymore. I'm using version 2.2.9 of the extension

![image](https://github.com/HassakuTb/TwitterImageDownloader2/assets/40332939/14fef193-66e5-486b-a958-49707a930525)

**Comment by HassakuTb** [comment]
Thank you for your report.

![image](https://github.com/HassakuTb/TwitterImageDownloader2/assets/18409473/d9f14e16-73b9-4e25-b4b8-3d55c7000869)

Please click the addon icon and set "Can always read and change data on this site".
Will this method improve the issue?

**Comment by bea831333** [comment]
@HassakuTb Thanks for the response.

It is already set for me
![image](https://github.com/HassakuTb/TwitterImageDownloader2/assets/40332939/e230f5ca-a0fc-41ac-851a-6398821dcd25)

**Comment by HassakuTb** [comment]
@bea831333

Firefox add-ons behavior is unclear.
I think it may be related to the fact that this upgrade supports ManifestV3, but I don't know for sure, sorry.

But there are reports of improvement by trying the following operations.

### reinstall add-on
1. copy and save your own filename template.
2. uninstall add-on.
3. install add-on again.
4. restore your settings.

### allow permissions
1. open `about:addons`.
2. click the add-on and open permissions tab.
3. turn all switches on.

### clean storage
1. open option page.
5. check or uncheck "Show Save As dislogues" checkbox.
6. copy your own filename template and click "Set to default".
7. click "Save" button.
8. restore your own settings and click "Save" again.
9. restart browser.

### enable manifest version3 (dangerous operation)
This operation should not be necessary. If you have operated it before, it might make sense.
1. open `about:config`
2. make `extensions.manifestV3.enabled` true

**Comment by bea831333** [comment]
@HassakuTb 
Uninstalling and reinstalling fixed the issue. I didn't get a chance to test the other three. I still don't know what caused the issue but I'll mark this as resolved now. Thanks
