### ISSUE TITLE
カスタムファイル名の中にツイートの日付を挿入する

### ISSUE THREAD

**Issue by Cyoudgax** [HassakuTb/TwitterImageDownloader2#8]
このように：「<userid>-<tweetdate>-<tweetid>-<imageindex>.<ext>」、例えば：「yoneyamai-2019-12-21-1208237152095490048-0.jpg」

**Comment by HassakuTb** [comment]
ご要望ありがとうございます。
こちら手軽に変更可能な内容ではありませんので、折を見て対応したいと思います。
拡張機能の保守の優先度はどうしても低くなるので、気長にお待ちください。

**Comment by HassakuTb** [comment]
### 開発用情報

twitter.com
対象tweetのarticleの子孫要素に以下のようにtimeタグでtimestampが打たれている
```html
<time datetime="2021-02-02T10:17:34.000Z">12時間</time>
```

tweetdeck.twitter.com
こちらはheader要素の子要素としてtimeタグが実装されている
```html
<time class="tweet-timestamp js-timestamp txt-mute flex-shrink--0" datetime="2021-02-02T21:17:52.000Z" data-time="1612300672000">  <a class="txt-size-variable--12 no-wrap" href="xxxxxx" rel="url" target="_blank">12:17</a>  </time>
```

**Comment by HassakuTb** [comment]
ISO8601フォーマットなので標準時に直すにはブラウザからtimezoneを引っ張ってこないといけない
もしくは設定項目にtimezone設定を追加するか
ちょっと難しいかも

**Comment by HassakuTb** [comment]
2.2.9で対応
